name: Process
on:
  schedule:
    - cron: "05 03 * * *"
    - cron: "05 11 * * *"
  workflow_dispatch:

env:
  # time zone
  TZ: Asia/Shanghai

  # GitHub Gist 配置 (添加这两行)
  GIST_PAT: ${{ secrets.GIST_PAT }}
  GIST_LINK: ${{ secrets.GIST_LINK }}

  # network proxy aggregate config
  SUBSCRIBE_CONF: ${{ secrets.SUBSCRIBE_CONF }}

  # token (添加默认值，避免为空)
  PUSH_TOKEN: ${{ secrets.PUSH_TOKEN || '' }}

  # network reachable (添加默认值)
  REACHABLE: ${{ vars.REACHABLE || 'true' }}

  # not check connective (添加默认值)
  SKIP_ALIVE_CHECK: ${{ vars.SKIP_ALIVE_CHECK || 'false' }}

  # skip remark (添加默认值)
  SKIP_REMARK: ${{ vars.SKIP_REMARK || 'false' }}

  # workflow mode (添加默认值)
  WORKFLOW_MODE: ${{ vars.WORKFLOW_MODE || 'normal' }}

  # include special protocols, such vless hysteria2 and hysteria
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS || 'true' }}

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Debug Environment
        run: |
          echo "GIST_PAT: ${GIST_PAT:0:5}***"  # 打印前5个字符用于调试
          echo "GIST_LINK: ${GIST_LINK}"
          echo "SUBSCRIBE_CONF: ${SUBSCRIBE_CONF:0:5}***"
          echo "PUSH_TOKEN: ${PUSH_TOKEN:0:5}***"
          echo "REACHABLE: ${REACHABLE}"
          echo "SKIP_ALIVE_CHECK: ${SKIP_ALIVE_CHECK}"
          echo "SKIP_REMARK: ${SKIP_REMARK}"
          echo "WORKFLOW_MODE: ${WORKFLOW_MODE}"
          echo "ENABLE_SPECIAL_PROTOCOLS: ${ENABLE_SPECIAL_PROTOCOLS}"

      - name: Process
        run: python -u subscribe/process.py --overwrite

      - name: Timestamp
        run: date

      - name: Timestamp
        run: date
